run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - revive
    - errcheck
    - unused

issues:
  exclude-use-default: false

output:
  formats: colored-line-number
